Revert "Enable patchelf.rb for HOMEBREW_DEVELOPERs."
This reverts commit d6338f0b91a767d3665e85a8730d8e94f8bb927d.

Fix the error:
brew install patchelf
==> Pouring patchelf-0.10.x86_64_linux.bottle.1.tar.gz
Error: cannot load such file -- patchelf