Revert "test-bot: revise Step output transcoding and XML character filtering"
This reverts commit d45f63dedb7dafbad435582c5873704111a5ca54.

```
==> git clean -ffdx
HEAD is now at d45f63d test-bot: revise Step output transcoding and XML character filtering
Removing Library/Homebrew/test/.bundle/
Removing Library/Homebrew/test/fs_leak_log
Removing Library/Homebrew/test/vendor/
Error: invalid regular expression: /[^

 -uD7FFuE000-uFFFDu{10000}-u{10FFFF}]/
```
Using Ruby 1.8.